version: '3'

services:
  postgres:
      image: postgres:latest
      volumes:
          - /pg:/var/lib/postgresql/data
      command: createdb jd

  go:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: jd
    volumes:
      - .:/go/src/jd
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=jd
